name: Build TWRP Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
          libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
          xsltproc unzip bc python2

    - name: Set up repo
      run: |
        mkdir ~/bin || true
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+rx ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

    - name: Sync TWRP source
      run: |
        mkdir -p ~/twrp && cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
        repo sync -j4 --force-sync

    - name: Copy device tree
      run: |
        mkdir -p ~/twrp/device/samsung/
        cp -r $GITHUB_WORKSPACE/device/samsung/j7xlte ~/twrp/device/samsung/

    - name: Start build
      run: |
        cd ~/twrp
        source build/envsetup.sh
        lunch omni_j7xlte-eng
        mka recoveryimage

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: twrp-j7xlte
        path: ~/twrp/out/target/product/j7xlte/recovery.img
